image: node:18

stages:
  - install
  - lint
  - test
  - build
  - security

cache:
  paths:
    - node_modules/

variables:
  CI: true

before_script:
  - npm install -g npm@latest
  - npm ci

install:
  stage: install
  script:
    - echo "Dependencies installed using npm ci"

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - echo "Build step placeholder – React Native usually builds in Xcode/Android Studio"
    - npm run android || true  # Avoid breaking CI on local-only build steps

security:
  stage: security
  script:
    - npx audit-ci --moderate
  allow_failure: true
