image: node:18 # Use an image with Node.js pre-installed

stages:
  - install
  - lint
  - test
  - build
  - security

# Install dependencies (including React Native dependencies)
install_dependencies:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install
    # - cd ios && pod install && cd ..

# Linting job to ensure code quality
lint:
  stage: lint
  script:
    - echo "Running ESLint..."
    - npm run lint # Ensure you have ESLint configured for your project

# Static Application Security Testing (SAST)
sast:
  stage: security
  include:
    - template: Security/SAST.gitlab-ci.yml

# Unit tests (you can adjust based on your test suite)
test:
  stage: test
  script:
    - echo "Running tests..."
    - npm test # Ensure you have your tests set up (e.g., Jest or Mocha)

# Build the APK for Android
build_android:
  stage: build
  script:
    - echo "Building Android APK..."
    - cd android && ./gradlew assembleRelease && cd ..

# Optionally, you can add a deploy stage
# deploy:
#   stage: deploy
#   script:
#     - echo "Deploying APK to Firebase App Distribution (or any other service)"
#     # - firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk --app <your-app-id>
#   only:
#     - main  # Deploy only when pushing to the main branch
