image: node:18 # Use an image with Node.js pre-installed

stages:
  - install
  - test
  - lint
  - build
  - security

# Include external templates (e.g., for security scanning)
include:
  - template: Security/SAST.gitlab-ci.yml

# Install dependencies (including React Native dependencies)
install_dependencies:
  stage: install
  script:
    - echo "Installing dependencies started..."
    - npm install
    - echo "Installing dependencies ended..."

   
  cache:
    paths:
      - node_modules/  # Cache node_modules to speed up future runs
    # If you use Yarn, uncomment the line below and adjust
    # paths:
    #   - ~/.cache/yarn

# # Linting job to ensure code quality
# lint:
#   stage: lint
#   script:
#     - echo "Running ESLint..."
#     - npm run lint # Ensure you have ESLint configured for your project

# # Unit tests (you can adjust based on your test suite)
# test:
#   stage: test
#   script:
#     - echo "Running tests..."
#     - npx jest # Use npx to ensure jest is run from node_modules
#     # Optional: Log the installed Jest version to confirm installation
#     - npm list jest

# Build the APK for Android
build_android:
  stage: build
  script:
    - echo "Building Android APK..."
    - cd android && ./gradlew assembleRelease && cd ..
