image: node:18

stages:
  - install
  - test
  - lint
  - build
  - security

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"

# Install Node modules and Java
install_dependencies:
  stage: install
  script:
    - echo "Installing dependencies..."
    - apt-get update && apt-get install -y openjdk-17-jdk
    - npm install
  cache:
    paths:
      - node_modules/

# Lint
lint:
  stage: lint
  script:
    - echo "Running ESLint..."
    - npm run lint

# Run tests
test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm test
  cache:
    paths:
      - node_modules/

# Build Android APK
build_android:
  stage: build
  script:
    - echo "Installing JDK..."
    - apt-get update && apt-get install -y openjdk-17-jdk
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - echo "JAVA_HOME set to $JAVA_HOME"

    - echo "Installing Node.js dependencies..."
    - npm install

    - echo "Building Android APK..."
    - cd android && ./gradlew assembleRelease && cd ..
  cache:
    paths:
      - node_modules/
      - android/.gradle
